spring:
  application:
    name: minio-file-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fileservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/fileservice
          jwk-set-uri: http://localhost:8080/auth/realms/fileservice/protocol/openid-connect/certs

server:
  port: 8081
  servlet:
    context-path: /api

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: fileservice
  secure: false

openfga:
  api-url: http://localhost:8080
  store-id: 01FXNV56HVSN3GPT3BGTJ5FPHC
  authorization-model-id: 01FXNV56HVSN3GPT3BGTJ5FPHD

file:
  default-expiry-days: 7
  allowed-content-types:
    - image/jpeg
    - image/png
    - image/gif
    - application/pdf
    - application/msword
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/vnd.ms-excel
    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - text/plain

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.fileservice.minioservice.controller
